web:
  build: .
  ports:
   - "5000:5000"
  links:
   - aerospike
  hostname: dev.awesome-counter.com
  environment:
    - AEROSPIKE_HOST=dev_aerospike_1   
aerospike:
  image: aerospike/aerospike-server
  volumes: 
    - $PWD:/opt/aerospike/etc
