haproxy-server:
  image: ehazlett/interlock:latest
  environment:
   - "DOCKER_HOST"
  volumes:
  # boot2docker images use the following location for certificates etc.
   - "/var/lib/boot2docker:/etc/docker"
  ports:
   - "80:8080"
  command: "--swarm-url=$DOCKER_HOST --swarm-tls-ca-cert=/etc/docker/ca.pem --swarm-tls-cert=/etc/docker/server.pem --swarm-tls-key=/etc/docker/server-key.pem --debug --plugin haproxy start"
haproxy-app:
  hostname: prod.awesome-counter.com
  ports:
  - 5000
